In [64]:
from pathlib import Path
import pandas as pd
import numpy as np
from accr.utils.data import train_test_split_custom
from accr.data.processing import Processing

processing = Processing()

In [65]:
HERE = Path.cwd().parent.parent
DATASET_PATH = HERE / 'dataset'
DATASET_PATH

PosixPath('/home/godwin/Documents/academic/esgi/s1/hackaton/hackaton-accr/dataset')

In [66]:
import sys
sys.path.append(str(HERE))

In [67]:
# Récupérer les données
train_ds =  pd.read_csv(f'{DATASET_PATH}/preprocessed_data.csv')
processing.summary(train_ds)

{'Missing Values': atm      0
 choc     0
 surf     0
 catr     0
 situ     0
 manv     0
 obs      0
 locp     0
 plan     0
 infra    0
 circ     0
 secu2    0
 etatp    0
 secu3    0
 obsm     0
 grav     0
 vosp     0
 int      0
 catv     0
 secu1    0
 vma      0
 prof     0
 col      0
 lum      0
 dtype: int64,
 'Constant Features': []}

In [68]:
# Conversion de toutes les colonnes en int, tout en gérant les erreurs pour les colonnes non numériques
train_ds = train_ds.apply(pd.to_numeric, errors='coerce')
processing.summary(train_ds)

{'Missing Values': atm      0
 choc     0
 surf     0
 catr     0
 situ     0
 manv     0
 obs      0
 locp     0
 plan     0
 infra    0
 circ     0
 secu2    0
 etatp    0
 secu3    0
 obsm     0
 grav     0
 vosp     0
 int      0
 catv     0
 secu1    0
 vma      0
 prof     0
 col      0
 lum      0
 dtype: int64,
 'Constant Features': []}

In [69]:
train_ds.head()

atm  choc  surf  catr  situ  manv  obs  locp  plan  infra  ...  obsm  grav  \
0  2.0   5.0   2.0     4   1.0   1.0  0.0   0.0   1.0    0.0  ...   0.0   4.0   
1  2.0   5.0   2.0     4   1.0   1.0  0.0   0.0   1.0    0.0  ...   0.0   4.0   
2  3.0   1.0   2.0     3   1.0   1.0  0.0   0.0   1.0    0.0  ...   1.0   1.0   
3  3.0   1.0   2.0     3   1.0   1.0  0.0   2.0   1.0    0.0  ...   1.0   3.0   
4  2.0   1.0   2.0     3   1.0  16.0  0.0   0.0   1.0    5.0  ...   2.0   3.0   

   vosp  int  catv  secu1   vma  prof  col  lum  
0   0.0  4.0  30.0    2.0  30.0   1.0  7.0  1.0  
1   0.0  4.0  30.0    2.0  30.0   1.0  7.0  1.0  
2   2.0  1.0   7.0    1.0  50.0   1.0  6.0  5.0  
3   2.0  1.0   7.0    0.0  50.0   1.0  6.0  5.0  
4   0.0  3.0   2.0    2.0  50.0   1.0  1.0  1.0  

[5 rows x 24 columns]

In [70]:
train_ds.dtypes

atm      float64
choc     float64
surf     float64
catr       int64
situ     float64
manv     float64
obs      float64
locp     float64
plan     float64
infra    float64
circ     float64
secu2    float64
etatp    float64
secu3    float64
obsm     float64
grav     float64
vosp     float64
int      float64
catv     float64
secu1    float64
vma      float64
prof     float64
col      float64
lum      float64
dtype: object

In [71]:
import torch

In [ ]:
# Split data
y = train_ds['grav']
y = y - 1
X = train_ds.drop(columns=['grav'])



X_train, X_test, y_train, y_test = train_test_split_custom(X, y, test_size=0.2, random_state=42)
X_train = (X_train - np.mean(X_train)) / np.std(X_train, axis=0)
X_test = (X_test - np.mean(X_train)) / np.std(X_train, axis=0)


# Convert to tensor
X_train = torch.tensor(X_train.values, dtype=torch.float32)
X_test = torch.tensor(X_test.values, dtype=torch.float32)
y_train = torch.tensor(y_train.values, dtype=torch.long)
y_test = torch.tensor(y_test.values, dtype=torch.long)

In [73]:
# Vérification des NaN et des infinis
print(torch.isnan(X_train).any(), torch.isinf(X_train).any())  # Vérifier dans X_train
print(torch.isnan(X_test).any(), torch.isinf(X_test).any())    # Vérifier dans X_test


tensor(False) tensor(False)
tensor(False) tensor(False)


In [77]:
from collections import Counter


In [78]:
Counter(y_train.numpy())

Counter({np.int64(0): 56671,
         np.int64(3): 51947,
         np.int64(2): 19113,
         np.int64(1): 3090})

In [74]:
torch.unique(y_train)

tensor([0, 1, 2, 3])

In [75]:
np.unique(y)

array([0., 1., 2., 3.])

In [76]:
y = y - 1
np.unique(y)

array([-1.,  0.,  1.,  2.])